import type { Metadata } from "next";
import { fontPrimary, fontSecondary } from "../styles/fonts";
import "../styles/globals.css";
import Header from "@/components/common/header/index";
import Footer from "@/components/common/footer/index";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${fontPrimary.variable} ${fontSecondary.variable} font-secondary`}
      >
        <div>
          <Header />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
