import type { Metadata } from "next";
import { fontPrimary, fontSecondary } from "../assets/styles/fonts";
import "../assets/styles/globals.css";
import { HeaderContainer } from "@/domains/layout/containers/header-container";
import { FooterContainer } from "@/domains/layout/containers/footer-container";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${fontPrimary.variable} ${fontSecondary.variable} font-secondary`}
      >
        <div>
          <HeaderContainer />
          {children}
          <FooterContainer />
        </div>
      </body>
    </html>
  );
}
