import type { Metadata } from "next";
import { fontPrimary, fontSecondary } from "../styles/fonts";
import "../styles/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${fontPrimary.variable} ${fontSecondary.variable} font-secondary`}>
        {children}
      </body>
    </html>
  );
}
